# Generated by Django 3.2.6 on 2021-09-20 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название ролика')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления ролика')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения записи')),
                ('photo', models.ImageField(blank=True, upload_to='ClipsPhotos/%Y/%m/%d/', verbose_name='Превью')),
            ],
            options={
                'verbose_name': 'Ролик',
                'verbose_name_plural': 'Ролики',
            },
        ),
        migrations.CreateModel(
            name='scr_res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scr_res_1', models.IntegerField(default=384, verbose_name='Разрешение видео')),
                ('scr_res_2', models.IntegerField(default=288, verbose_name='Разрешение видео')),
            ],
            options={
                'verbose_name': 'Разрешение',
                'verbose_name_plural': 'Разрешение',
            },
        ),
        migrations.CreateModel(
            name='Scr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('nameb', models.IntegerField(verbose_name='Номер экрана')),
                ('Dir', models.CharField(default='atv', max_length=50, verbose_name='Ресурс')),
                ('ip_add', models.GenericIPAddressField(verbose_name='IP_адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения записи')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото экрана')),
                ('Check', models.BooleanField(default=True, verbose_name='Активен')),
                ('scr_res', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='FReport.scr_res', verbose_name='Разрешение видео')),
            ],
            options={
                'verbose_name': 'Экран',
                'verbose_name_plural': 'Экраны',
            },
        ),
        migrations.CreateModel(
            name='PhotoRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('Clips_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FReport.clips')),
                ('Scr_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FReport.scr')),
            ],
            options={
                'verbose_name': 'Фото_отчеты',
                'verbose_name_plural': 'Фото_отчет',
            },
        ),
        migrations.AddField(
            model_name='clips',
            name='scr_res',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='FReport.scr_res', verbose_name='Разрешение видео'),
        ),
    ]
