# Generated by Django 3.2.6 on 2021-09-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FReport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clips',
            old_name='scr_res',
            new_name='scr_res_id',
        ),
        migrations.RemoveField(
            model_name='clips',
            name='photo',
        ),
        migrations.AlterField(
            model_name='scr',
            name='ip_add',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP_адрес'),
        ),
    ]
