# Generated by Django 3.2.6 on 2021-09-27 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FReport', '0002_auto_20210921_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clips',
            name='scr_res_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='FReport.scr_res', verbose_name='Разрешение видео'),
        ),
        migrations.AlterField(
            model_name='scr',
            name='ip_add',
            field=models.GenericIPAddressField(default='10.10.0.1', verbose_name='IP_адрес'),
        ),
        migrations.AlterField(
            model_name='scr',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Название'),
        ),
    ]
