# Generated by Django 3.2.6 on 2021-09-27 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FReport', '0003_auto_20210927_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='photorep',
            name='data_report',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата фотоотчета'),
            preserve_default=False,
        ),
    ]
